
name: CI/CD

on:
  push:
    branches: [ "Pipeline" ]
    paths:
      - 'Backend/**'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Clean
        working-directory: Backend  # Cambia al directorio 'Backend'
        run: mvn clean
      - name: Build
        working-directory: Backend  # Cambia al directorio 'Backend'
        run: mvn -B package

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Clean
        working-directory: Backend  # Cambia al directorio 'Backend'
        run: mvn clean
      - name: Build
        working-directory: Backend  # Cambia al directorio 'Backend'
        run: mvn -B package
      - name: Test
        working-directory: Backend  # Cambia al directorio 'Backend'
        run: mvn test